# Generated by Django 3.2 on 2021-05-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210426_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='time',
        ),
    ]
