# Generated by Django 3.2 on 2021-05-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_courses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='language',
            field=models.CharField(choices=[('1', 'Казакша'), ('2', 'Русский'), ('3', 'English')], default=1, max_length=2, verbose_name='Язык'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
